### PR TITLE
[JENKINS-37430] Add support for ppc64le

### PR DESCRIPTION
**Pull request by kuisathaverat**
[JENKINS-37430](https://issues.jenkins-ci.org/browse/JENKINS-37430)

@reviewbybees 
it adds support for Power8 platform, these are the commits related with the PR

 
https://github.com/jnr/jffi/commit/7e22759c08f4a0dc9e3a9158829bf853fbe08e9c
https://github.com/jnr/jnr-unixsocket/commit/767ed30357a1c21ecfd6b474142e01c10a5c5c8b
https://github.com/jnr/jnr-ffi/commit/6d8cdc0ce1a5d6dcfbec5c3b635bfe3232088273

### CODE REVIEW

**Comment by kuisathaverat** [comment]
@stephenc WDYT about this upgrade of plugins to support ppc64le

**Comment by stephenc** [comment]
Did you check if Jenkins has been updated to match?

This is somewhat similar to the bouncycastle issue

**Comment by kuisathaverat** [comment]
@stephenc in core there are a previous version of jnr-posix, I am going to review if it works without touch it in both sides.

```
<dependency>
      <groupId>com.github.jnr</groupId>
      <artifactId>jnr-posix</artifactId>
      <version>3.0.1</version>
</dependency>
```

**Comment by kuisathaverat** [comment]
@stephenc I tested that we can keep jnr-posix on same version of core

**Comment by kuisathaverat** [comment]
@reviewbybees Please, if someone can review it will be appreciated

**Comment by abayer** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
Would be nice to see the full list of changes in libs.
I suppose we pick much more than a particular fix. Regarding the custom build of `1.0.3.1-jenkins-20276`, we should ensure that the all fixes from this custom build are integrated to the upstream

**Comment by jglick** [comment]
> we should ensure that the all fixes from this custom build are integrated to the upstream

Right, I think that is the main task.

**Comment by kuisathaverat** [comment]
@jglick @oleg-nenashev AFAIT by the last comment in https://github.com/jnr/jnr-ffi/pull/23, JENKINS-20276 it is not longer an issue on this library

**Comment by kuisathaverat** [comment]
@reviewbybees done

**Pull request closed without merging**
